[package]
name = "async_cache"
version = "0.1.0"
authors = ["Isaac Whitfield <iw@whitfin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
tokio = { version = "1", features = ["time", "sync"] }

[dev.dependencies]
tokio = { version = "1", features = ["full"] }
